import { canonicalHash, canonicalJson, errorMessage } from "./safety.js";
import {
  buildTrainingWeek,
  TrainingWeekDraftSchema,
  type TrainingWeekDraft,
} from "./program.js";
import { withWriteLock } from "./write-lock.js";

export type GarminWorkoutTransport = {
  listWorkouts(): Promise<Record<string, unknown>[]>;
  createWorkout(
    payload: Record<string, unknown>
  ): Promise<Record<string, unknown>>;
  scheduleWorkout(workoutId: number, date: string): Promise<unknown>;
  isWorkoutScheduled(workoutId: number, date: string): Promise<boolean>;
  getWorkoutSchedules(
    year: number
  ): Promise<{ workoutId: number; date: string }[]>;
  getWorkout(workoutId: number): Promise<Record<string, unknown>>;
};

type State = {
  marker: string;
  workoutId?: number;
  date: string;
  state: "missing" | "created" | "scheduled" | "verified" | "conflict";
};

type PlannedWorkout = {
  workout: TrainingWeekDraft["workouts"][number];
  workoutId?: number;
  alreadyScheduled: boolean;
};

function numberId(value: unknown): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value <= 0) {
    throw new Error("Garmin did not return a valid workoutId");
  }
  return value;
}

function containsExpected(actual: unknown, expected: unknown): boolean {
  if (Array.isArray(expected)) {
    return (
      Array.isArray(actual) &&
      actual.length === expected.length &&
      expected.every((item, index) => containsExpected(actual[index], item))
    );
  }
  if (expected && typeof expected === "object") {
    if (!actual || typeof actual !== "object") return false;
    return Object.entries(expected as Record<string, unknown>)
      .filter(([childKey]) => childKey !== "stepOrder")
      .every(([childKey, item]) =>
        containsExpected((actual as Record<string, unknown>)[childKey], item)
      );
  }
  return Object.is(actual, expected);
}

function markerOf(workout: Record<string, unknown>): string {
  return typeof workout.description === "string" ? workout.description : "";
}

export class TrainingService {
  constructor(private readonly garmin: GarminWorkoutTransport) {}

  async apply(input: TrainingWeekDraft, hash: string, confirmed: boolean) {
    return withWriteLock(() => this.applyLocked(input, hash, confirmed));
  }

  private async applyLocked(
    input: TrainingWeekDraft,
    hash: string,
    confirmed: boolean
  ) {
    const draft = TrainingWeekDraftSchema.parse(input);
    if (!confirmed) throw new Error("Explicit confirmation is required");
    if (canonicalHash(draft) !== hash)
      throw new Error("Approved draft hash does not match");
    if (draft.healthBlockers.length)
      throw new Error("Health blocker prevents workout writes");
    const age = Date.now() - Date.parse(draft.evidence.observedAt);
    if (age > 6 * 60 * 60 * 1000 || age < -5 * 60 * 1000) {
      throw new Error("Coaching snapshot is stale; preview the week again");
    }
    const rebuilt = buildTrainingWeek({
      weekStart: draft.weekStart,
      weekNumber: draft.weekNumber,
      recoveryAction: draft.recoveryAction,
      healthBlockers: draft.healthBlockers,
      evidence: draft.evidence,
    });
    if (canonicalJson(rebuilt) !== canonicalJson(draft)) {
      throw new Error("Training draft was not generated by the week preview");
    }

    const existing = await this.garmin.listWorkouts();
    const schedules = new Map<number, string[]>();
    for (const year of new Set(
      draft.workouts.map(({ date }) => Number(date.slice(0, 4)))
    )) {
      for (const schedule of await this.garmin.getWorkoutSchedules(year)) {
        const dates = schedules.get(schedule.workoutId) ?? [];
        if (!dates.includes(schedule.date)) dates.push(schedule.date);
        schedules.set(schedule.workoutId, dates);
      }
    }
    const created: { workoutId: number; marker: string }[] = [];
    const scheduled: { workoutId: number; date: string }[] = [];
    const states: State[] = [];
    const planned: PlannedWorkout[] = [];

    for (const workout of draft.workouts) {
      const candidates = existing.filter((item) =>
        markerOf(item).includes(workout.marker)
      );
      if (candidates.length > 1)
        throw new Error(`Conflict: duplicate marker ${workout.marker}`);
      const workoutId =
        candidates.length === 1 ? numberId(candidates[0].workoutId) : undefined;
      if (workoutId !== undefined) {
        const actual = await this.garmin.getWorkout(workoutId);
        if (!containsExpected(actual, workout.payload)) {
          throw new Error(
            `Conflict: marker exists with different payload: ${workout.marker}`
          );
        }
        const existingDates = schedules.get(workoutId) ?? [];
        if (existingDates.some((date) => date !== workout.date)) {
          throw new Error(
            `Conflict: workout ${workoutId} is scheduled on a different date`
          );
        }
        planned.push({
          workout,
          workoutId,
          alreadyScheduled: existingDates.includes(workout.date),
        });
      } else {
        planned.push({ workout, alreadyScheduled: false });
      }
    }

    for (const plan of planned) {
      const { workout } = plan;
      const state: State = {
        marker: workout.marker,
        workoutId: plan.workoutId,
        date: workout.date,
        state: plan.workoutId === undefined ? "missing" : "created",
      };
      states.push(state);
      try {
        let workoutId = plan.workoutId;
        if (workoutId === undefined) {
          const result = await this.garmin.createWorkout(workout.payload);
          workoutId = numberId(result.workoutId);
          created.push({ workoutId, marker: workout.marker });
          state.workoutId = workoutId;
          state.state = "created";
        }
        if (!plan.alreadyScheduled) {
          await this.garmin.scheduleWorkout(workoutId, workout.date);
          scheduled.push({ workoutId, date: workout.date });
        }
        state.state = "scheduled";

        const readBack = await this.garmin.getWorkout(workoutId);
        if (!containsExpected(readBack, workout.payload)) {
          throw new Error(`Read-back mismatch for workout ${workoutId}`);
        }
        if (!(await this.garmin.isWorkoutScheduled(workoutId, workout.date))) {
          throw new Error(
            `Read-back schedule mismatch for workout ${workoutId}`
          );
        }
        state.state = "verified";
      } catch (error) {
        if (/conflict/i.test(errorMessage(error))) throw error;
        return {
          status: "partial",
          error: errorMessage(error),
          created,
          scheduled,
          states,
        } as const;
      }
    }

    return { status: "verified", created, scheduled, states } as const;
  }

  async verify(input: TrainingWeekDraft) {
    const draft = TrainingWeekDraftSchema.parse(input);
    const existing = await this.garmin.listWorkouts();
    const results = [];
    for (const workout of draft.workouts) {
      const candidates = existing.filter((item) =>
        markerOf(item).includes(workout.marker)
      );
      if (candidates.length !== 1) {
        results.push({
          marker: workout.marker,
          date: workout.date,
          verified: false,
          reason: candidates.length ? "duplicate-marker" : "missing",
        });
        continue;
      }
      const candidate = candidates[0];
      const workoutId = numberId(candidate.workoutId);
      const actual = await this.garmin.getWorkout(workoutId);
      const payloadMatches = containsExpected(actual, workout.payload);
      const dateMatches = await this.garmin.isWorkoutScheduled(
        workoutId,
        workout.date
      );
      results.push({
        marker: workout.marker,
        workoutId,
        date: workout.date,
        payloadMatches,
        dateMatches,
        verified: payloadMatches && dateMatches,
        expectedFingerprint: canonicalHash(workout.payload),
        actualManagedFingerprint: payloadMatches
          ? canonicalHash(workout.payload)
          : canonicalHash(actual),
      });
    }
    return {
      verified:
        results.length === draft.workouts.length &&
        results.every((item) => item.verified),
      proposalFingerprint: canonicalHash(draft),
      results,
      canonicalDraft: canonicalJson(draft),
    };
  }
}
